//App.setPreference('AutoHideSplashScreen', 'true');

//ref: http://docs.meteor.com/#/full/mobileconfigjs
// This section sets up some basic app metadata,
// the entire section is optional.
App.info({
  id: 'ca.knowledge.bopinput',
  version: '0.0.9',
  name: 'BOP Input',
  description: 'Data collection app for BOP',
  author: 'ABCD',
  email: 'andrew@abcd.ca',
  website: 'http://input.bop.nyc'
});

App.accessRule("http://maps.googleapis.com");
App.accessRule("http://bop-images.s3-website-us-west-1.amazonaws.com");
App.accessRule("http://meteor.local/*");
//// Set up resources such as icons and launch screens.
//App.icons({
//	'iphone': 'icons/icon-60.png',
//	'iphone_2x': 'icons/icon-60@2x.png',
//	// ... more screen sizes and platforms ...
//});
//
//App.launchScreens({
//	'iphone': 'splash/Default~iphone.png',
//	'iphone_2x': 'splash/Default@2x~iphone.png',
//	// ... more screen sizes and platforms ...
//});
//
//// Set PhoneGap/Cordova preferences
//App.setPreference('BackgroundColor', '0xff0000ff');
//App.setPreference('HideKeyboardFormAccessoryBar', true);
//
//// Pass preferences for a particular PhoneGap/Cordova plugin
//App.configurePlugin('com.phonegap.plugins.facebookconnect', {
//	APP_ID: '1234567890',
//	API_KEY: 'supersecretapikey'
//});

// ---
// generated by js2coffee 2.0.4